name: file_picker
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker_platform_interface:
    path: ../file_picker_platform_interface
  file_picker_web:
    path: ../file_picker_web
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.file_picker
        pluginClass: FilePickerPlugin
      ios:
        pluginClass: FilePickerPlugin
      web:
        default_plugin: file_picker_web
